language: java

branches:
    only:
        - master

install:
- ./gradle/jvm-setup.sh
- java -version

script:
- ./gradlew build

deploy:
  # Upload binaries
  - provider: s3
    on:
      branch:
        - master
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "downloads.ortussolutions.com"
    local-dir: build/libs
    upload-dir: cfmlprojects
    acl: public_read