language: java

branches:
    only:
        - master

script:
- ./gradlew build
- cd build
- cd libs
- ls

deploy:
  # Upload binaries
  - provider: s3
    on:
      branch:
        - master
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "downloads.ortussolutions.com"
    local-dir: build/libs
    upload-dir: cfmlprojects/javashim
    acl: public_read